#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

SRC_DIR="../video"
OUT_DIR="public/frames"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

FRAME_STRIDE=2
BASE_WIDTH=1280
MOBILE_WIDTH=720
WEBP_QUALITY=78
CLIPS=(01 02 03 04 05)

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/$BASE_WIDTH" "$OUT_DIR/$MOBILE_WIDTH"

GLOBAL_INDEX=0
FRAMES_PER_CLIP=()

for CLIP in "${CLIPS[@]}"; do
  CLIP_TMP="$TMP_DIR/$CLIP"
  mkdir -p "$CLIP_TMP"

  ffmpeg -y -loglevel error -i "$SRC_DIR/$CLIP.mp4" \
    -vf "select='not(mod(n\,${FRAME_STRIDE}))',scale=${BASE_WIDTH}:-2" \
    -fps_mode passthrough -start_number 0 \
    "$CLIP_TMP/frame_%04d.png"

  COUNT=0
  for PNG in "$CLIP_TMP"/frame_*.png; do
    OUT_NAME=$(printf "%04d.webp" "$GLOBAL_INDEX")
    cwebp -quiet -q "$WEBP_QUALITY" -m 6 "$PNG" -o "$OUT_DIR/$BASE_WIDTH/$OUT_NAME"
    cwebp -quiet -q "$WEBP_QUALITY" -m 6 -resize "$MOBILE_WIDTH" 0 "$PNG" -o "$OUT_DIR/$MOBILE_WIDTH/$OUT_NAME"
    GLOBAL_INDEX=$((GLOBAL_INDEX + 1))
    COUNT=$((COUNT + 1))
  done
  FRAMES_PER_CLIP+=("$COUNT")
  echo "Clip $CLIP: $COUNT frames"
done

FRAMES_PER_CLIP_CSV=$(printf ",%s" "${FRAMES_PER_CLIP[@]}")
FRAMES_PER_CLIP_CSV=${FRAMES_PER_CLIP_CSV:1}

mkdir -p src/generated
cat > src/generated/frameManifest.ts <<EOF
// AUTO-GENERATED by scripts/extract-frames.sh — do not hand-edit.
export const FRAME_COUNT = ${GLOBAL_INDEX};
export const FRAMES_PER_CLIP = [${FRAMES_PER_CLIP_CSV}] as const;

/** Available frame widths, ascending. The mobile tier comes first. */
export const TIERS = [${MOBILE_WIDTH}, ${BASE_WIDTH}] as const;
export type Tier = (typeof TIERS)[number];
EOF

# Tiny blurred stand-in for frame 0, inlined into the bundle so the first
# screen shows something before any frame has been fetched.
LQIP_PNG="$TMP_DIR/lqip.png"
LQIP_JPG="$TMP_DIR/lqip.jpg"
ffmpeg -y -loglevel error -i "$SRC_DIR/${CLIPS[0]}.mp4" -frames:v 1 \
  -vf "scale=32:-2,gblur=sigma=1.2" "$LQIP_PNG"
sips -s format jpeg -s formatOptions 55 "$LQIP_PNG" --out "$LQIP_JPG" >/dev/null

cat > src/generated/lqip.ts <<EOF
// AUTO-GENERATED by scripts/extract-frames.sh — do not hand-edit.
export const LQIP_DATA_URI =
  "data:image/jpeg;base64,$(base64 -i "$LQIP_JPG" | tr -d '\n')";
EOF

echo "Total frames: $GLOBAL_INDEX"
du -sh "$OUT_DIR/$BASE_WIDTH" "$OUT_DIR/$MOBILE_WIDTH"
echo "LQIP: $(wc -c < "$LQIP_JPG") bytes"
